enum ForecastParamsActions {
	SET_MODEL_ID = 'SET_MODEL_ID',
	SET_TEMPERATURE = 'SET_TEMPERATURE',
	SET_ATMOSPHERIC_PRESSURE = 'SET_ATMOSPHERIC_PRESSURE',
	SET_HUMIDITY = 'SET_HUMIDITY',
	SET_WIND_SPEED = 'SET_WIND_SPEED',
	SET_CLOUDINESS = 'SET_CLOUDINESS',
	SET_HOUR = 'SET_HOUR',
	SET_SEASON = 'SET_SEASON',
}

export default ForecastParamsActions
