name: Check
on: push
jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v3
   - uses: pnpm/action-setup@v3
     with:
      version: 8
   - name: Install deps
     run: pnpm install
   - name: Lint
     run: pnpm run lint
 build-as-test:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v3
   - uses: pnpm/action-setup@v3
     with:
      version: 8
   - name: Install deps
     run: pnpm install
   - name: Build
     run: pnpm run build